version: "3.8"

services:
  db:
    image: postgres:15-alpine3.20
    container_name: postgres15
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=modular_db
      - POSTGRES_USER=openpg
      - POSTGRES_PASSWORD=lu7nX34ug3
    networks:
      - cloudflare_networks

  web:
    build: .
    container_name: modular_web
    restart: always
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      gunicorn modularSystem.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cloudflare_networks

volumes:
  postgres_data:
  static_volume:
networks:
  cloudflare_networks:
    external: true
